# Generated by Django 5.2.10 on 2026-02-18 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('formato', models.CharField(choices=[('Vinilo', 'Vinilo'), ('CD', 'CD'), ('Cassette', 'Cassette')], max_length=20)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)])),
                ('discografica', models.CharField(max_length=200)),
                ('num_pistas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('formato', models.CharField(choices=[('VHS', 'VHS'), ('CD', 'CD'), ('DVD', 'DVD')], max_length=20)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)])),
                ('duracion_minutos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('genero', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AutorPublicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_publicaciones', to='publicaciones.autor')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_publicaciones', to='publicaciones.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='AutorDisco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='publicaciones.autor')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='socios.disco')),
            ],
        ),
        migrations.CreateModel(
            name='AutorVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='publicaciones.autor')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='socios.video')),
            ],
        ),
    ]
